"""Flagship Polymarket research study.

Research question: does a calibrated probability forecast beat the market's own
implied probability by enough to survive spread, fees, and capital lock-up?

The design mirrors the equities flagship study and inherits its discipline.
Forecasts are generated by chronological walk-forward refits, calibration is
fitted on strictly later data than the model it calibrates, and the ML entrants
are scored against baselines that are hard to beat for the right reason:

``Market price``
    The efficient-market null. Its forecast *is* the price, so its measured
    edge is exactly zero and every trade it would place loses the spread.
``Favourite`` / ``Longshot``
    Fixed tilts toward the expensive and the cheap side. These are the classical
    prediction-market bias tests, and because they always clear the edge gate by
    construction they show what trading without an edge actually costs.

The headline metric is the Brier skill score against the market price, not
accuracy. Predicting that a market quoted at 0.9 resolves YES is not skill.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import numpy as np
import pandas as pd

from quant_system.config import load_config
from quant_system.evaluation.experiment import save_experiment
from quant_system.evaluation.robustness import block_bootstrap_mean, percentile_interval
from quant_system.polymarket.arbitrage import opportunities_frame, scan_markets
from quant_system.polymarket.backtest import (
    TradeConfig,
    run_backtest,
    theoretical_break_even_edge,
)
from quant_system.polymarket.features import build_snapshot_features, design_matrix
from quant_system.polymarket.metrics import forecast_report
from quant_system.polymarket.model import (
    default_model,
    market_anchored_boosted_model,
    market_anchored_model,
)
from quant_system.polymarket.simulation import PanelSpec, simulate_panel, simulate_arbitrage_snapshot
from quant_system.polymarket.validation import (
    achievable_brier_skill,
    fold_diagnostics,
    resolution_aware_walk_forward,
)

ROOT = Path(__file__).resolve().parents[1]


def load_panel(config: dict, force_simulation: bool = False) -> tuple[pd.DataFrame, str]:
    """Return the snapshot panel and a label describing where it came from."""
    panel_path = ROOT / config["data"]["panel_csv"]
    if not force_simulation and panel_path.exists():
        panel = pd.read_csv(panel_path, parse_dates=["timestamp", "end_date"])
        if len(panel) > 0:
            return panel, "live"
    simulation_cfg = config["simulation"]
    spec = PanelSpec(
        n_markets=int(simulation_cfg["n_markets"]),
        observations_per_market=int(simulation_cfg["observations_per_market"]),
        horizon_days=int(simulation_cfg["horizon_days"]),
        mispricing_sigma=float(simulation_cfg["mispricing_sigma"]),
        signal_strength=float(simulation_cfg["signal_strength"]),
        mispricing_decay=float(simulation_cfg["mispricing_decay"]),
        spread=float(simulation_cfg["spread"]),
        seed=int(simulation_cfg["seed"]),
    )
    return simulate_panel(spec), "simulation"


def baseline_tilt(trade_config: TradeConfig) -> float:
    """Smallest fixed mispricing claim that still clears the live edge gate.

    The backtester shrinks every forecast toward the market price and charges
    entry frictions, so a tilt chosen without accounting for both produces
    baselines that place no trades and therefore diagnose nothing. Solving
    ``(1 - shrinkage) * tilt - friction >= min_edge`` gives the tilt that makes
    the comparison informative.
    """
    friction = theoretical_break_even_edge(
        0.5,
        trade_config.default_spread + 2 * trade_config.extra_slippage,
        trade_config.fee_bps,
    )
    return (trade_config.min_edge + friction) / max(1.0 - trade_config.shrinkage, 1e-6) * 1.05


def baseline_probabilities(price: pd.Series, tilt: float) -> dict[str, pd.Series]:
    """Forecasts that require no model, for benchmarking the ML entrants."""
    favourite = np.where(price >= 0.5, price + tilt, price - tilt)
    return {
        "Market price": price.copy(),
        "Favourite": pd.Series(np.clip(favourite, 0.01, 0.99), index=price.index),
        "Longshot": pd.Series(np.clip(2.0 * price - favourite, 0.01, 0.99), index=price.index),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=str(ROOT / "configs" / "polymarket.yaml"))
    parser.add_argument(
        "--simulation",
        action="store_true",
        help="ignore any cached live panel and run against synthetic markets",
    )
    args = parser.parse_args()

    config = load_config(args.config)
    frictions, risk_cfg = config["frictions"], config["risk"]
    model_cfg, research_cfg = config["model"], config["research"]

    panel, source = load_panel(config, force_simulation=args.simulation)
    print(f"Panel source: {source} | {len(panel)} rows, {panel['market_id'].nunique()} markets")

    passthrough = [
        column
        for column in model_cfg.get("passthrough_features", []) or []
        if column in panel.columns
    ]
    if passthrough:
        print(f"Passthrough features: {', '.join(passthrough)}")
    frame = build_snapshot_features(
        panel,
        momentum_windows=tuple(model_cfg["momentum_windows"]),
        volatility_window=int(model_cfg["volatility_window"]),
        passthrough_columns=passthrough,
    )
    X, y, _ = design_matrix(frame)
    print(f"Design matrix: {X.shape[0]} observations x {X.shape[1]} features")

    timestamps = frame.loc[X.index, "timestamp"]
    if "end_date" not in frame.columns:
        raise ValueError(
            "panel needs an end_date column: without settlement times the study cannot "
            "restrict training to markets that had already resolved"
        )
    resolution_times = frame.loc[X.index, "end_date"]
    price = frame.loc[X.index, "price"].astype(float)

    # One market quoted a hundred times is one outcome, not a hundred. Weighting
    # by the reciprocal observation count stops repeated snapshots of the same
    # settled market from dominating the likelihood.
    observation_counts = frame.loc[X.index].groupby("market_id")["price"].transform("size")
    sample_weight = (1.0 / observation_counts.astype(float)).rename("sample_weight")

    test_window = int(research_cfg["walk_forward_test_window"])
    min_train = int(research_cfg["walk_forward_min_train_size"])
    embargo_days = float(research_cfg.get("embargo_days", 0.0))
    folds = fold_diagnostics(timestamps, resolution_times, test_window, min_train, embargo_days)
    if folds.empty:
        raise ValueError(
            f"No fold had {min_train} observations from already-settled markets. "
            "The panel is too short or too few of its markets have resolved."
        )
    print(f"Folds: {len(folds)} | cold start until {folds['test_start'].iloc[0].date()}")

    trade_config = TradeConfig(
        bankroll=float(risk_cfg["bankroll"]),
        fee_bps=float(frictions["fee_bps"]),
        default_spread=float(frictions["default_spread"]),
        extra_slippage=float(frictions["extra_slippage"]),
        kelly_multiplier=float(risk_cfg["kelly_multiplier"]),
        max_fraction=float(risk_cfg["max_fraction_per_market"]),
        max_total_exposure=float(risk_cfg["max_total_exposure"]),
        min_edge=float(risk_cfg["min_edge"]),
        shrinkage=float(risk_cfg["shrinkage"]),
        max_drawdown=float(risk_cfg["max_drawdown"]),
        drawdown_floor=float(risk_cfg["drawdown_floor"]),
        one_trade_per_market=bool(risk_cfg["one_trade_per_market"]),
        min_notional=float(risk_cfg["min_notional"]),
    )

    tilt = baseline_tilt(trade_config)
    forecasts: dict[str, pd.Series] = dict(baseline_probabilities(price, tilt))

    anchor_alpha = model_cfg.get("anchor_alpha", "auto")
    linear = market_anchored_model(alpha=anchor_alpha)
    linear.alpha_grid = tuple(model_cfg["anchor_alpha_grid"])
    boosted = market_anchored_boosted_model(
        alpha=anchor_alpha, random_state=int(model_cfg["random_state"])
    )
    boosted.alpha_grid = tuple(model_cfg["boosted_alpha_grid"])
    models = {
        # Included to show what anchoring buys: this entrant treats the market
        # price as an ordinary feature and has to re-estimate its coefficient.
        "Logistic (unanchored)": default_model(
            random_state=int(model_cfg["random_state"]), method=str(model_cfg["method"])
        ),
        "Market-anchored linear": linear,
        "Market-anchored boosted": boosted,
    }
    for name, model in models.items():
        print(f"Walk-forward refits for {name} ...")
        forecasts[name] = resolution_aware_walk_forward(
            model,
            X,
            y,
            timestamps,
            resolution_times,
            test_window=test_window,
            min_train_size=min_train,
            embargo_days=embargo_days,
            sample_weight=sample_weight if name != "Logistic (unanchored)" else None,
        )

    ceiling = float("nan")
    if "true_probability" in frame.columns:
        ceiling = achievable_brier_skill(
            y, frame.loc[X.index, "true_probability"].astype(float), price
        )

    rows: list[dict] = []
    for name, probability in forecasts.items():
        if probability.empty:
            continue
        scorecard = forecast_report(
            y.reindex(probability.index), probability, price.reindex(probability.index)
        )
        result = run_backtest(frame.loc[X.index], probability, trade_config)

        ci_low, ci_high = float("nan"), float("nan")
        if len(result.trades) >= 20:
            per_trade = (result.trades["profit"] / result.trades["capital"]).dropna()
            bootstrap = block_bootstrap_mean(
                per_trade,
                n_bootstrap=int(research_cfg["bootstrap_samples"]),
                block_size=int(research_cfg["bootstrap_block"]),
                seed=int(model_cfg["random_state"]),
            )
            ci_low, ci_high = percentile_interval(bootstrap)

        rows.append(
            {
                "strategy": name,
                **scorecard,
                **result.summary,
                "skill_captured": scorecard["brier_skill_vs_market"] / ceiling
                if np.isfinite(ceiling) and ceiling != 0
                else float("nan"),
                "mean_trade_return_ci_low": ci_low,
                "mean_trade_return_ci_high": ci_high,
            }
        )
        print(
            f"  {name:24s} trades={result.summary['n_trades']:5.0f} "
            f"BSS={scorecard['brier_skill_vs_market']:+.5f} "
            f"ROI={result.summary['roi_on_capital']:+.4f}"
        )

    results = pd.DataFrame(rows)
    report_dir = ROOT / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    results_path = report_dir / "polymarket_results.csv"
    results.to_csv(results_path, index=False)

    fixture = simulate_arbitrage_snapshot()
    scan = opportunities_frame(
        scan_markets(
            fixture.markets,
            fixture.books,
            fixture.groups,
            fee_bps=float(frictions["fee_bps"]),
            max_capital=float(config["arbitrage"]["max_capital_per_basket"]),
            min_profit=float(config["arbitrage"]["min_profit"]),
            min_shares=float(config["arbitrage"]["min_shares"]),
        )
    )
    planted = sum(len(value) for value in fixture.planted.values())

    report_path = _write_report(
        report_dir / "polymarket_research_report.md",
        source=source,
        panel=panel,
        X=X,
        results=results,
        trade_config=trade_config,
        price=price,
        scan_found=len(scan),
        scan_planted=planted,
        config=config,
        tilt=tilt,
        passthrough=passthrough,
        ceiling=ceiling,
        folds=folds,
    )

    record = save_experiment(
        report_dir / "experiments",
        "polymarket_oos_study",
        config,
        {
            "panel_source": source,
            "n_observations": int(len(X)),
            "n_markets": int(panel["market_id"].nunique()),
            "n_folds": int(len(folds)),
            "n_strategies": int(len(results)),
            "achievable_brier_skill": float(ceiling),
            "arbitrage_planted": planted,
            "arbitrage_detected": int(len(scan)),
        },
        {
            "git_commit": os.getenv("GIT_COMMIT", "unknown"),
            "results_csv": str(results_path.relative_to(ROOT)),
            "report": str(report_path.relative_to(ROOT)),
        },
    )
    print(f"\n{report_path.relative_to(ROOT)}")
    print(record.relative_to(ROOT))


def _fmt(value: float, spec: str = ".4f") -> str:
    if value is None:
        return "—"
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    return "—" if not np.isfinite(number) else f"{number:{spec}}"


def _write_report(
    path: Path,
    source: str,
    panel: pd.DataFrame,
    X: pd.DataFrame,
    results: pd.DataFrame,
    trade_config: TradeConfig,
    price: pd.Series,
    scan_found: int,
    scan_planted: int,
    config: dict,
    tilt: float,
    passthrough: list[str],
    ceiling: float,
    folds: pd.DataFrame,
) -> Path:
    """Write the research narrative, tables, and the caveats they depend on."""
    median_price = float(price.median())
    break_even = theoretical_break_even_edge(
        median_price,
        trade_config.default_spread + 2 * trade_config.extra_slippage,
        trade_config.fee_bps,
    )
    provenance = (
        "**Live Polymarket data.** The panel was built from settled markets and their "
        "recorded CLOB price history, so the results below are measurements of the real venue."
        if source == "live"
        else
        "**Synthetic data.** No cached Polymarket panel was present, so the study ran on "
        "generated markets in which an exploitable edge exists *by construction* "
        f"(`signal_strength = {config['simulation']['signal_strength']}`). These numbers "
        "validate that sizing, frictions, settlement, leakage control, and capital "
        "accounting are wired together correctly. They are **not** evidence of edge on "
        "Polymarket. Run `scripts/fetch_polymarket_data.py` to replace this panel with "
        "real settled markets."
    )

    lines = [
        "# Polymarket Prediction-Market Research Study",
        "",
        "> Research question: does a calibrated probability forecast beat the market's own "
        "implied probability by enough to survive spread, fees, and capital lock-up?",
        "",
        "## Data provenance",
        "",
        provenance,
        "",
        "## Experimental design",
        "",
        f"- Panel: {len(panel)} snapshots across {panel['market_id'].nunique()} markets; "
        f"{len(X)} usable observations after feature warm-up.",
        f"- Features: {X.shape[1]} columns, each computed from the market's own past and "
        "lagged one observation.",
        f"- Out-of-sample rule: {len(folds)} chronological blocks, each trained only on "
        "markets that had **already settled** when the block began. A market's snapshots "
        "therefore cannot appear on both sides of a split, and no label is used before it "
        "was knowable.",
        f"- Cold start: no forecast is produced before {folds['test_start'].iloc[0].date()}, "
        f"by which point {folds['n_train'].iloc[0]} observations from settled markets exist.",
        f"- Frictions: {trade_config.default_spread:.3f} spread + "
        f"{trade_config.extra_slippage:.3f} adverse selection + "
        f"{trade_config.fee_bps:.1f} bps fee, charged on entry.",
        f"- Sizing: {trade_config.kelly_multiplier:.2f} x Kelly, capped at "
        f"{trade_config.max_fraction:.1%} per market and "
        f"{trade_config.max_total_exposure:.0%} aggregate, with forecasts shrunk "
        f"{trade_config.shrinkage:.0%} toward the market price.",
        f"- Edge gate: {trade_config.min_edge:.3f}. At the median price of "
        f"{median_price:.3f} the break-even edge is {break_even:.4f}, so the gate is "
        f"{'above' if trade_config.min_edge > break_even else 'BELOW'} the friction floor.",
        "- Positions are held to settlement; committed capital is unavailable to later trades.",
        f"- Baseline tilt: {tilt:.4f}, the smallest fixed mispricing claim that still clears "
        "the gate after shrinkage and frictions.",
        (
            f"- Passthrough features supplied by the caller: `{'`, `'.join(passthrough)}`. "
            "These are trusted, not validated for look-ahead."
            if passthrough
            else "- No passthrough features; every column derives from price, book, and time."
        ),
        "",
        "## Forecast quality",
        "",
        "Skill is measured against the market price, not against a coin flip. A positive "
        "Brier skill score means the forecast carries information the price does not.",
        "",
    ]
    if np.isfinite(ceiling):
        lines += [
            f"**The achievable skill here is {ceiling:+.5f}.** That is what an oracle holding "
            "the true probabilities would score against this price series. Brier score on "
            "binary outcomes is dominated by the irreducible variance `q(1 - q)`, so skill "
            "against a roughly efficient price is always a few thousandths even when the "
            "economic edge is large. Read every number below as a fraction of that ceiling, "
            "not against 1.0.",
            "",
        ]
    lines += [
        "| Strategy | Observations | Brier | Market Brier | Brier skill vs market | % of ceiling | Calibration error |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in results.to_dict(orient="records"):
        lines.append(
            f"| {row['strategy']} | {row['n_observations']:.0f} | "
            f"{_fmt(row['brier_score'], '.5f')} | {_fmt(row['market_brier_score'], '.5f')} | "
            f"{_fmt(row['brier_skill_vs_market'], '+.5f')} | "
            f"{_fmt(row.get('skill_captured', float('nan')) * 100, '+.1f')} | "
            f"{_fmt(row['calibration_error'])} |"
        )

    lines += [
        "",
        "## Trading results after frictions",
        "",
        "| Strategy | Trades | ROI on capital | Total return | Hit rate | Max drawdown | Mean trade return | 95% CI |",
        "|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in results.to_dict(orient="records"):
        interval = (
            f"[{row['mean_trade_return_ci_low']:+.4f}, {row['mean_trade_return_ci_high']:+.4f}]"
            if np.isfinite(row["mean_trade_return_ci_low"])
            else "—"
        )
        lines.append(
            f"| {row['strategy']} | {row['n_trades']:.0f} | "
            f"{_fmt(row['roi_on_capital'], '+.4f')} | {_fmt(row['total_return'], '+.4f')} | "
            f"{_fmt(row['hit_rate'])} | {_fmt(row['max_drawdown'])} | "
            f"{_fmt(row['mean_trade_return'], '+.4f')} | {interval} |"
        )

    lines += [
        "",
        "## Edge realization",
        "",
        "Realized profit per share regressed on the edge predicted before the trade. A slope "
        "near one means predicted edge materialized; a slope near zero means the forecast "
        "carried no information about outcomes and the trading was noise.",
        "",
        "An edge gate accepts trades only in a narrow band of predicted edge, which leaves "
        "the regressor with little spread against a payoff that swings a full dollar. Read "
        "the slope next to its standard error: a large slope with a larger standard error is "
        "noise, not evidence.",
        "",
        "| Strategy | Slope | Std error | t | R² | Mean predicted edge | Mean realized edge |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in results.to_dict(orient="records"):
        lines.append(
            f"| {row['strategy']} | {_fmt(row.get('edge_slope'), '+.3f')} | "
            f"{_fmt(row.get('edge_slope_std_error'), '.3f')} | "
            f"{_fmt(row.get('edge_slope_t_stat'), '+.2f')} | "
            f"{_fmt(row.get('edge_r_squared'))} | "
            f"{_fmt(row.get('edge_mean_predicted_edge'), '+.4f')} | "
            f"{_fmt(row.get('edge_mean_realized_edge'), '+.4f')} |"
        )

    lines += [
        "",
        "## Structural arbitrage self-test",
        "",
        f"The scanner was run against a synthetic snapshot containing {scan_planted} planted "
        f"basket mispricings and reported {scan_found}. Because the planted set is known "
        "exactly, this checks the scanner for both false negatives and false positives; it "
        "says nothing about how many such baskets exist on the live venue. Run "
        "`scripts/scan_polymarket_arbitrage.py --source live` for that.",
        "",
        "## How to read this",
        "",
        "1. Start with **Brier skill vs market**, as a fraction of the achievable ceiling. If "
        "it is not positive, the forecast has no edge and the trading columns are measuring "
        "luck plus frictions.",
        "2. Check that **Market price** trades rarely or loses. It has zero edge by "
        "definition, so profit from it would indicate a bug in the friction model.",
        "3. Compare against **Favourite** and **Longshot**. These always clear the edge gate "
        "without any information, so they price what trading on a false signal costs.",
        "4. Compare **Market-anchored** against **Logistic (unanchored)**. The unanchored "
        "entrant must re-estimate the coefficient on the market price from a few hundred "
        "independent settled markets; the anchored one takes that coefficient as one and "
        "learns only a correction. The gap between them is the cost of that free parameter.",
        "5. Only then read ROI, and read it next to the **edge realization** slope and the "
        "trade count. A high ROI on a few dozen binary settlements is not a result.",
        "",
        "## Limitations",
        "",
        "- Entries assume the quoted size is available; prediction-market books are thin and "
        "a real order moves them.",
        "- Resolution risk is not modelled: markets can settle on a technicality, be disputed, "
        "or resolve differently from the plain reading of the question.",
        "- Capital lock-up until settlement is modelled, but the opportunity cost of that "
        "capital is not.",
        "- Settled markets are a survivorship-inflected sample; markets that were voided or "
        "never resolved do not appear in the panel.",
        "- Multiple models were examined, which creates researcher degrees of freedom. The "
        "regularization strength is chosen inside each training window rather than from these "
        "results, but the choice of model family was not. Treat a single positive result as a "
        "hypothesis, not a finding.",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


if __name__ == "__main__":
    main()
