"""Flagship Polymarket research study.

Research question: does a calibrated probability forecast beat the market's own
implied probability by enough to survive spread, fees, and capital lock-up?

The design mirrors the equities flagship study and inherits its discipline.
Forecasts are generated by chronological walk-forward refits, calibration is
fitted on strictly later data than the model it calibrates, and the ML entrants
are scored against baselines that are hard to beat for the right reason:

``Market price``
    The efficient-market null. Its forecast *is* the price, so its measured
    edge is exactly zero and every trade it would place loses the spread.
``Favourite`` / ``Longshot``
    Fixed tilts toward the expensive and the cheap side. These are the classical
    prediction-market bias tests, and because they always clear the edge gate by
    construction they show what trading without an edge actually costs.

The headline metric is the Brier skill score against the market price, not
accuracy. Predicting that a market quoted at 0.9 resolves YES is not skill.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import numpy as np
import pandas as pd

from quant_system.config import load_config
from quant_system.evaluation.experiment import save_experiment
from quant_system.evaluation.robustness import block_bootstrap_mean, percentile_interval
from quant_system.polymarket.arbitrage import opportunities_frame, scan_markets
from dataclasses import replace

from quant_system.polymarket.correlation import (
    block_correlation,
    concentration_report,
    outcome_concordance,
)
from quant_system.polymarket.backtest import (
    TradeConfig,
    run_backtest,
    theoretical_break_even_edge,
)
from quant_system.polymarket.features import build_snapshot_features, design_matrix
from quant_system.polymarket.market_making import (
    QuoteConfig,
    break_even_uninformed_rate,
    sweep_uninformed_fill_rate,
)
from quant_system.polymarket.metrics import forecast_report
from quant_system.polymarket.pricing import max_tolerable_resolution_risk
from quant_system.polymarket.model import (
    default_model,
    market_anchored_boosted_model,
    market_anchored_model,
)
from quant_system.polymarket.simulation import PanelSpec, simulate_panel, simulate_arbitrage_snapshot
from quant_system.polymarket.validation import (
    achievable_brier_skill,
    fold_diagnostics,
    resolution_aware_walk_forward,
)

ROOT = Path(__file__).resolve().parents[1]


def load_panel(config: dict, force_simulation: bool = False) -> tuple[pd.DataFrame, str]:
    """Return the snapshot panel and a label describing where it came from."""
    panel_path = ROOT / config["data"]["panel_csv"]
    if not force_simulation and panel_path.exists():
        panel = pd.read_csv(panel_path, parse_dates=["timestamp", "end_date"])
        if len(panel) > 0:
            return panel, "live"
    simulation_cfg = config["simulation"]
    spec = PanelSpec(
        n_markets=int(simulation_cfg["n_markets"]),
        observations_per_market=int(simulation_cfg["observations_per_market"]),
        horizon_days=int(simulation_cfg["horizon_days"]),
        mispricing_sigma=float(simulation_cfg["mispricing_sigma"]),
        signal_strength=float(simulation_cfg["signal_strength"]),
        mispricing_decay=float(simulation_cfg["mispricing_decay"]),
        spread=float(simulation_cfg["spread"]),
        n_themes=int(simulation_cfg.get("n_themes", 0)),
        theme_strength=float(simulation_cfg.get("theme_strength", 0.0)),
        seed=int(simulation_cfg["seed"]),
    )
    return simulate_panel(spec), "simulation"


def baseline_tilt(trade_config: TradeConfig) -> float:
    """Smallest fixed mispricing claim that still clears the live edge gate.

    The backtester shrinks every forecast toward the market price and charges
    entry frictions, so a tilt chosen without accounting for both produces
    baselines that place no trades and therefore diagnose nothing. Solving
    ``(1 - shrinkage) * tilt - friction >= min_edge`` gives the tilt that makes
    the comparison informative.
    """
    friction = theoretical_break_even_edge(
        0.5,
        trade_config.default_spread + 2 * trade_config.extra_slippage,
        trade_config.fee_bps,
    )
    return (trade_config.min_edge + friction) / max(1.0 - trade_config.shrinkage, 1e-6) * 1.05


def baseline_probabilities(price: pd.Series, tilt: float) -> dict[str, pd.Series]:
    """Forecasts that require no model, for benchmarking the ML entrants."""
    favourite = np.where(price >= 0.5, price + tilt, price - tilt)
    return {
        "Market price": price.copy(),
        "Favourite": pd.Series(np.clip(favourite, 0.01, 0.99), index=price.index),
        "Longshot": pd.Series(np.clip(2.0 * price - favourite, 0.01, 0.99), index=price.index),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=str(ROOT / "configs" / "polymarket.yaml"))
    parser.add_argument(
        "--simulation",
        action="store_true",
        help="ignore any cached live panel and run against synthetic markets",
    )
    args = parser.parse_args()

    config = load_config(args.config)
    frictions, risk_cfg = config["frictions"], config["risk"]
    model_cfg, research_cfg = config["model"], config["research"]

    panel, source = load_panel(config, force_simulation=args.simulation)
    print(f"Panel source: {source} | {len(panel)} rows, {panel['market_id'].nunique()} markets")

    passthrough = [
        column
        for column in model_cfg.get("passthrough_features", []) or []
        if column in panel.columns
    ]
    if passthrough:
        print(f"Passthrough features: {', '.join(passthrough)}")
    frame = build_snapshot_features(
        panel,
        momentum_windows=tuple(model_cfg["momentum_windows"]),
        volatility_window=int(model_cfg["volatility_window"]),
        passthrough_columns=passthrough,
    )
    X, y, _ = design_matrix(frame)
    print(f"Design matrix: {X.shape[0]} observations x {X.shape[1]} features")

    timestamps = frame.loc[X.index, "timestamp"]
    if "end_date" not in frame.columns:
        raise ValueError(
            "panel needs an end_date column: without settlement times the study cannot "
            "restrict training to markets that had already resolved"
        )
    resolution_times = frame.loc[X.index, "end_date"]
    market_ids = frame.loc[X.index, "market_id"]
    price = frame.loc[X.index, "price"].astype(float)

    # One market quoted a hundred times is one outcome, not a hundred. Weighting
    # by the reciprocal observation count stops repeated snapshots of the same
    # settled market from dominating the likelihood.
    observation_counts = frame.loc[X.index].groupby("market_id")["price"].transform("size")
    sample_weight = (1.0 / observation_counts.astype(float)).rename("sample_weight")

    test_window = int(research_cfg["walk_forward_test_window"])
    min_train = int(research_cfg["walk_forward_min_train_size"])
    embargo_days = float(research_cfg.get("embargo_days", 0.0))
    folds = fold_diagnostics(
        timestamps, resolution_times, market_ids, test_window, min_train, embargo_days
    )
    if folds.empty:
        raise ValueError(
            f"No fold had {min_train} observations from already-settled markets. "
            "The panel is too short or too few of its markets have resolved."
        )
    print(f"Folds: {len(folds)} | cold start until {folds['test_start'].iloc[0].date()}")

    trade_config = TradeConfig(
        bankroll=float(risk_cfg["bankroll"]),
        fee_bps=float(frictions["fee_bps"]),
        default_spread=float(frictions["default_spread"]),
        extra_slippage=float(frictions["extra_slippage"]),
        kelly_multiplier=float(risk_cfg["kelly_multiplier"]),
        max_fraction=float(risk_cfg["max_fraction_per_market"]),
        max_total_exposure=float(risk_cfg["max_total_exposure"]),
        min_edge=float(risk_cfg["min_edge"]),
        shrinkage=float(risk_cfg["shrinkage"]),
        max_drawdown=float(risk_cfg["max_drawdown"]),
        drawdown_floor=float(risk_cfg["drawdown_floor"]),
        one_trade_per_market=bool(risk_cfg["one_trade_per_market"]),
        min_notional=float(risk_cfg["min_notional"]),
        resolution_risk=float(risk_cfg["resolution_risk"]),
        resolution_recovery=float(risk_cfg["resolution_recovery"]),
        resolution_seed=int(model_cfg["random_state"]),
    )

    tilt = baseline_tilt(trade_config)
    forecasts: dict[str, pd.Series] = {}

    anchor_alpha = model_cfg.get("anchor_alpha", "auto")
    linear = market_anchored_model(alpha=anchor_alpha)
    linear.alpha_grid = tuple(model_cfg["anchor_alpha_grid"])
    boosted = market_anchored_boosted_model(
        alpha=anchor_alpha, random_state=int(model_cfg["random_state"])
    )
    boosted.alpha_grid = tuple(model_cfg["boosted_alpha_grid"])
    models = {
        # Included to show what anchoring buys: this entrant treats the market
        # price as an ordinary feature and has to re-estimate its coefficient.
        "Logistic (unanchored)": default_model(
            random_state=int(model_cfg["random_state"]), method=str(model_cfg["method"])
        ),
        "Market-anchored linear": linear,
        "Market-anchored boosted": boosted,
    }
    for name, model in models.items():
        print(f"Walk-forward refits for {name} ...")
        forecasts[name] = resolution_aware_walk_forward(
            model,
            X,
            y,
            timestamps,
            resolution_times,
            market_ids,
            test_window=test_window,
            min_train_size=min_train,
            embargo_days=embargo_days,
            sample_weight=sample_weight if name != "Logistic (unanchored)" else None,
        )

    # Every entrant must be scored on the same rows. The walk-forward models
    # produce nothing before the cold start, so baselines evaluated over the
    # full panel would be compared on an extra calendar window the models never
    # saw -- and trade count, ROI and total profit are all window-dependent.
    scored = pd.Index([])
    for probability in forecasts.values():
        scored = scored.union(probability.index)
    if len(scored) == 0:
        raise ValueError("no fold produced an out-of-sample forecast")
    print(f"Common out-of-sample sample: {len(scored)} of {len(X)} observations")

    for name, series in baseline_probabilities(price.loc[scored], tilt).items():
        forecasts[name] = series
    forecasts = {
        name: series.loc[series.index.intersection(scored)]
        for name, series in forecasts.items()
    }

    ceiling = float("nan")
    if "true_probability" in frame.columns:
        ceiling = achievable_brier_skill(
            y.loc[scored],
            frame.loc[scored, "true_probability"].astype(float),
            price.loc[scored],
        )

    order = [
        "Market price", "Favourite", "Longshot",
        "Logistic (unanchored)", "Market-anchored linear", "Market-anchored boosted",
    ]
    forecasts = {name: forecasts[name] for name in order if name in forecasts}

    rows: list[dict] = []
    for name, probability in forecasts.items():
        if probability.empty:
            continue
        scorecard = forecast_report(
            y.reindex(probability.index), probability, price.reindex(probability.index)
        )
        result = run_backtest(frame.loc[X.index], probability, trade_config)

        ci_low, ci_high = float("nan"), float("nan")
        if len(result.trades) >= 20:
            per_trade = (result.trades["profit"] / result.trades["capital"]).dropna()
            bootstrap = block_bootstrap_mean(
                per_trade,
                n_bootstrap=int(research_cfg["bootstrap_samples"]),
                block_size=int(research_cfg["bootstrap_block"]),
                seed=int(model_cfg["random_state"]),
            )
            ci_low, ci_high = percentile_interval(bootstrap)

        rows.append(
            {
                "strategy": name,
                **scorecard,
                **result.summary,
                "skill_captured": scorecard["brier_skill_vs_market"] / ceiling
                if np.isfinite(ceiling) and ceiling != 0
                else float("nan"),
                "mean_trade_return_ci_low": ci_low,
                "mean_trade_return_ci_high": ci_high,
            }
        )
        print(
            f"  {name:24s} trades={result.summary['n_trades']:5.0f} "
            f"BSS={scorecard['brier_skill_vs_market']:+.5f} "
            f"ROI={result.summary['roi_on_capital']:+.4f}"
        )

    results = pd.DataFrame(rows)
    velocity = _capital_velocity_study(config, frame.loc[X.index], forecasts, trade_config)
    concentration = _concentration_study(config, frame.loc[X.index], forecasts, trade_config)
    resolution = _resolution_risk_study(config, frame.loc[X.index], forecasts, trade_config)
    making = _market_making_study(config, frame.loc[X.index], forecasts)
    report_dir = ROOT / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    results_path = report_dir / "polymarket_results.csv"
    results.to_csv(results_path, index=False)
    velocity_path = report_dir / "polymarket_capital_velocity.csv"
    velocity.to_csv(velocity_path, index=False)
    resolution_path = report_dir / "polymarket_resolution_risk.csv"
    resolution.to_csv(resolution_path, index=False)
    making_path = report_dir / "polymarket_market_making.csv"
    pd.concat(
        [sweep.assign(fair_value=name) for name, sweep in making.items()], ignore_index=True
    ).to_csv(making_path, index=False)

    fixture = simulate_arbitrage_snapshot()
    scan = opportunities_frame(
        scan_markets(
            fixture.markets,
            fixture.books,
            fixture.groups,
            fee_bps=float(frictions["fee_bps"]),
            max_capital=float(config["arbitrage"]["max_capital_per_basket"]),
            min_profit=float(config["arbitrage"]["min_profit"]),
            min_shares=float(config["arbitrage"]["min_shares"]),
        )
    )
    planted = sum(len(value) for value in fixture.planted.values())

    report_path = _write_report(
        report_dir / "polymarket_research_report.md",
        source=source,
        panel=panel,
        X=X,
        results=results,
        trade_config=trade_config,
        price=price,
        scan_found=len(scan),
        scan_planted=planted,
        config=config,
        tilt=tilt,
        passthrough=passthrough,
        ceiling=ceiling,
        folds=folds,
        making=making,
        velocity=velocity,
        resolution=resolution,
        concentration=concentration,
    )

    record = save_experiment(
        report_dir / "experiments",
        "polymarket_oos_study",
        config,
        {
            "panel_source": source,
            "n_observations": int(len(X)),
            "n_markets": int(panel["market_id"].nunique()),
            "n_folds": int(len(folds)),
            "n_strategies": int(len(results)),
            "achievable_brier_skill": float(ceiling),
            "arbitrage_planted": planted,
            "arbitrage_detected": int(len(scan)),
        },
        {
            "git_commit": os.getenv("GIT_COMMIT", "unknown"),
            "results_csv": str(results_path.relative_to(ROOT)),
            "report": str(report_path.relative_to(ROOT)),
        },
    )
    print(f"\n{report_path.relative_to(ROOT)}")
    print(record.relative_to(ROOT))


def _capital_velocity_study(
    config: dict,
    frame: pd.DataFrame,
    forecasts: dict[str, pd.Series],
    base_config: TradeConfig,
) -> pd.DataFrame:
    """Run the same forecast under each exit rule and price the holding period.

    Comparing exit rules on ROI per trade answers the wrong question: a position
    held six months and one closed in a week score identically even though the
    second frees its capital fifty times over. The comparison here is profit per
    dollar-year of capital committed.
    """
    probability = forecasts.get("Market-anchored linear")
    if probability is None or probability.empty:
        return pd.DataFrame()

    rows = []
    for rule in config["risk"]["exit_rules"]:
        settings = replace(
            base_config,
            exit_edge_fraction=rule["exit_edge_fraction"],
            stop_loss_move=rule["stop_loss_move"],
        )
        result = run_backtest(frame, probability, settings)
        reasons = (
            result.trades["exit_reason"].value_counts().to_dict()
            if not result.trades.empty
            else {}
        )
        rows.append(
            {
                "exit_rule": rule["name"],
                **result.summary,
                "n_settlement": float(reasons.get("settlement", 0)),
                "n_convergence": float(reasons.get("convergence", 0)),
                "n_stop_loss": float(reasons.get("stop_loss", 0)),
            }
        )
        print(
            f"  {rule['name']:32s} trades={result.summary['n_trades']:4.0f} "
            f"hold={result.summary['mean_holding_days']:5.1f}d "
            f"per-capital-year={result.summary['roi_per_capital_year']:+.3f}"
        )
    return pd.DataFrame(rows)


def _concentration_study(
    config: dict,
    frame: pd.DataFrame,
    forecasts: dict[str, pd.Series],
    trade_config: TradeConfig,
) -> dict:
    """Ask whether the book's positions are as many bets as they are positions.

    The grouping is tested before it is trusted. A grouping that does not predict
    joint settlement on history would, if sized against, cut positions to control
    a concentration that is not there -- so the test runs first and the exposure
    figures are only computed from a correlation the data supports.
    """
    probability = forecasts.get("Market-anchored linear")
    if probability is None or probability.empty or "group" not in frame.columns:
        return {}

    settled = frame.groupby("market_id").agg(label=("label", "first"), group=("group", "first"))
    validation = outcome_concordance(
        settled["label"], settled["group"], seed=int(config["model"]["random_state"])
    )
    trusted = bool(validation["p_value"] < float(config["risk"].get("concentration_p_value", 0.01)))

    rho = validation["implied_within_correlation"] if trusted else 0.0
    grouping = settled["group"].to_dict()

    # The comparison that decides anything: the same forecast with the cluster
    # cap off and on. Reporting only the uncapped book would describe a
    # concentration the live path already prevents.
    # The cap is swept rather than asserted: whether it binds depends on how many
    # markets in one group happen to clear the edge gate at the same time, which
    # is a property of the universe and not something a default can know.
    rows = []
    for limit in config["risk"].get("cluster_exposure_sweep", [1.0]):
        result = run_backtest(
            frame, probability, replace(trade_config, max_cluster_exposure=float(limit)), grouping
        )
        if result.trades.empty:
            continue
        exposures = result.trades.groupby("market_id")["capital"].sum() / trade_config.bankroll
        sides = result.trades.groupby("market_id")["side"].first().to_dict()
        member = {market: grouping.get(market, market) for market in exposures.index}
        matrix = block_correlation(pd.Series(member), rho)
        rows.append(
            {
                "max_cluster_exposure": float(limit),
                **concentration_report(exposures, matrix, member, sides),
                "peak_group_exposure": float(
                    result.summary.get("peak_group_exposure", float("nan"))
                ),
                "total_profit": float(result.summary["total_profit"]),
                "roi_per_capital_year": float(result.summary["roi_per_capital_year"]),
            }
        )
    if not rows:
        return {"validation": validation, "trusted": trusted}

    sweep = pd.DataFrame(rows).sort_values("max_cluster_exposure", ascending=False)
    print(
        f"  grouping {'predicts' if trusted else 'does NOT predict'} joint settlement "
        f"(rho {validation['implied_within_correlation']:+.3f}, p={validation['p_value']:.3f})"
    )
    for row in sweep.to_dict(orient="records"):
        # The cap bound if the book ran right up against it; a peak comfortably
        # below means the per-market limit was already holding the group under.
        state = (
            "binds"
            if row["peak_group_exposure"] >= row["max_cluster_exposure"] - 1e-9
            else "dormant"
        )
        print(
            f"    cap {row['max_cluster_exposure']:>5.0%}: {row['n_positions']:>3.0f} positions = "
            f"{row['effective_independent_bets']:>5.1f} bets, peak group "
            f"{row['peak_group_exposure']:>5.1%}, profit {row['total_profit']:>+9,.0f} ({state})"
        )
    return {"validation": validation, "trusted": trusted, "sweep": sweep}


def _resolution_risk_study(
    config: dict,
    frame: pd.DataFrame,
    forecasts: dict[str, pd.Series],
    base_config: TradeConfig,
) -> pd.DataFrame:
    """Re-run the strategy assuming settlement is unreliable at various rates.

    Resolution risk works mainly by shutting trades down rather than by
    degrading the ones that survive: discounting the forecast pushes marginal
    positions below the edge gate. The trade count is therefore the robust
    reading here, and the P&L at high assumed risk rests on too few settlements
    to interpret.
    """
    probability = forecasts.get("Market-anchored linear")
    if probability is None or probability.empty:
        return pd.DataFrame()
    rows = []
    for risk in config["risk"]["resolution_risk_sweep"]:
        settings = replace(base_config, resolution_risk=float(risk))
        result = run_backtest(frame, probability, settings)
        rows.append({"resolution_risk": float(risk), **result.summary})
    return pd.DataFrame(rows)


def _market_making_study(
    config: dict,
    frame: pd.DataFrame,
    forecasts: dict[str, pd.Series],
) -> dict[str, pd.DataFrame]:
    """Sweep the maker's assumed flow mix, quoting around two fair values.

    Quoting around the market price isolates the spread-versus-adverse-selection
    trade-off with no informational advantage. Quoting around the model forecast
    adds one. Running both makes it visible whether the forecast is worth
    anything to a maker, which is a different question from whether it is worth
    anything to a taker.
    """
    settings = config["market_making"]
    rates = [float(rate) for rate in settings["sweep_rates"]]
    quote_config = QuoteConfig(
        half_spread=float(settings["half_spread"]),
        quote_size=float(settings["quote_size"]),
        max_inventory=float(settings["max_inventory"]),
        inventory_skew=float(settings["inventory_skew"]),
        max_concurrent_markets=int(settings["max_concurrent_markets"]),
        maker_fee_bps=float(settings["maker_fee_bps"]),
        uninformed_fill_rate=float(settings["uninformed_fill_rate"]),
        widen_within_days=float(settings["widen_within_days"]),
        widen_multiple=float(settings["widen_multiple"]),
        seed=int(config["model"]["random_state"]),
    )
    bankroll = float(settings["bankroll"])

    fair_values = {"Market price": None}
    anchored = forecasts.get("Market-anchored linear")
    if anchored is not None and not anchored.empty:
        fair_values["Market-anchored linear"] = anchored

    sweeps: dict[str, pd.DataFrame] = {}
    for name, values in fair_values.items():
        print(f"Market-making sweep quoting around {name} ...")
        sweeps[name] = sweep_uninformed_fill_rate(
            frame, rates, quote_config, values, bankroll
        )
    return sweeps


def _fmt(value: float, spec: str = ".4f") -> str:
    if value is None:
        return "—"
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    return "—" if not np.isfinite(number) else f"{number:{spec}}"


def _write_report(
    path: Path,
    source: str,
    panel: pd.DataFrame,
    X: pd.DataFrame,
    results: pd.DataFrame,
    trade_config: TradeConfig,
    price: pd.Series,
    scan_found: int,
    scan_planted: int,
    config: dict,
    tilt: float,
    passthrough: list[str],
    ceiling: float,
    folds: pd.DataFrame,
    making: dict[str, pd.DataFrame],
    velocity: pd.DataFrame,
    resolution: pd.DataFrame,
    concentration: dict,
) -> Path:
    """Write the research narrative, tables, and the caveats they depend on."""
    median_price = float(price.median())
    break_even = theoretical_break_even_edge(
        median_price,
        trade_config.default_spread + 2 * trade_config.extra_slippage,
        trade_config.fee_bps,
    )
    provenance = (
        "**Live Polymarket data.** The panel was built from settled markets and their "
        "recorded CLOB price history, so the results below are measurements of the real venue."
        if source == "live"
        else
        "**Synthetic data.** No cached Polymarket panel was present, so the study ran on "
        "generated markets in which an exploitable edge exists *by construction* "
        f"(`signal_strength = {config['simulation']['signal_strength']}`). These numbers "
        "validate that sizing, frictions, settlement, leakage control, and capital "
        "accounting are wired together correctly. They are **not** evidence of edge on "
        "Polymarket. Run `scripts/fetch_polymarket_data.py` to replace this panel with "
        "real settled markets."
    )

    lines = [
        "# Polymarket Prediction-Market Research Study",
        "",
        "> Research question: does a calibrated probability forecast beat the market's own "
        "implied probability by enough to survive spread, fees, and capital lock-up?",
        "",
        "## Data provenance",
        "",
        provenance,
        "",
        "## Experimental design",
        "",
        f"- Panel: {len(panel)} snapshots across {panel['market_id'].nunique()} markets; "
        f"{len(X)} usable observations after feature warm-up.",
        f"- Features: {X.shape[1]} columns, each computed from the market's own past and "
        "lagged one observation.",
        f"- Out-of-sample rule: {len(folds)} chronological blocks, each trained only on "
        "markets that had **already settled** when the block began. A market's snapshots "
        "therefore cannot appear on both sides of a split, and no label is used before it "
        "was knowable.",
        f"- Cold start: no forecast is produced before {folds['test_start'].iloc[0].date()}, "
        f"by which point {folds['n_train'].iloc[0]} observations from settled markets exist.",
        f"- Frictions: {trade_config.default_spread:.3f} spread + "
        f"{trade_config.extra_slippage:.3f} adverse selection + "
        f"{trade_config.fee_bps:.1f} bps fee, charged on entry.",
        f"- Sizing: {trade_config.kelly_multiplier:.2f} x Kelly, capped at "
        f"{trade_config.max_fraction:.1%} per market and "
        f"{trade_config.max_total_exposure:.0%} aggregate, with forecasts shrunk "
        f"{trade_config.shrinkage:.0%} toward the market price.",
        f"- Edge gate: {trade_config.min_edge:.3f}. At the median price of "
        f"{median_price:.3f} the break-even edge is {break_even:.4f}, so the gate is "
        f"{'above' if trade_config.min_edge > break_even else 'BELOW'} the friction floor.",
        "- Positions are held to settlement; committed capital is unavailable to later trades.",
        f"- Baseline tilt: {tilt:.4f}, the smallest fixed mispricing claim that still clears "
        "the gate after shrinkage and frictions.",
        (
            f"- Passthrough features supplied by the caller: `{'`, `'.join(passthrough)}`. "
            "These are trusted, not validated for look-ahead."
            if passthrough
            else "- No passthrough features; every column derives from price, book, and time."
        ),
        "",
        "## Forecast quality",
        "",
        "Skill is measured against the market price, not against a coin flip. A positive "
        "Brier skill score means the forecast carries information the price does not.",
        "",
    ]
    if np.isfinite(ceiling):
        lines += [
            f"**The achievable skill here is {ceiling:+.5f}.** That is what an oracle holding "
            "the true probabilities would score against this price series. Brier score on "
            "binary outcomes is dominated by the irreducible variance `q(1 - q)`, so skill "
            "against a roughly efficient price is always a few thousandths even when the "
            "economic edge is large. Read every number below as a fraction of that ceiling, "
            "not against 1.0.",
            "",
        ]
    lines += [
        "| Strategy | Observations | Brier | Market Brier | Brier skill vs market | % of ceiling | Calibration error |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in results.to_dict(orient="records"):
        lines.append(
            f"| {row['strategy']} | {row['n_observations']:.0f} | "
            f"{_fmt(row['brier_score'], '.5f')} | {_fmt(row['market_brier_score'], '.5f')} | "
            f"{_fmt(row['brier_skill_vs_market'], '+.5f')} | "
            f"{_fmt(row.get('skill_captured', float('nan')) * 100, '+.1f')} | "
            f"{_fmt(row['calibration_error'])} |"
        )

    lines += [
        "",
        "## Trading results after frictions",
        "",
        "| Strategy | Trades | ROI on capital | Total return | Hit rate | Max drawdown | Mean trade return | 95% CI |",
        "|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in results.to_dict(orient="records"):
        interval = (
            f"[{row['mean_trade_return_ci_low']:+.4f}, {row['mean_trade_return_ci_high']:+.4f}]"
            if np.isfinite(row["mean_trade_return_ci_low"])
            else "—"
        )
        lines.append(
            f"| {row['strategy']} | {row['n_trades']:.0f} | "
            f"{_fmt(row['roi_on_capital'], '+.4f')} | {_fmt(row['total_return'], '+.4f')} | "
            f"{_fmt(row['hit_rate'])} | {_fmt(row['max_drawdown'])} | "
            f"{_fmt(row['mean_trade_return'], '+.4f')} | {interval} |"
        )

    lines += [
        "",
        "## Edge realization",
        "",
        "Realized profit per share regressed on the edge predicted before the trade. A slope "
        "near one means predicted edge materialized; a slope near zero means the forecast "
        "carried no information about outcomes and the trading was noise.",
        "",
        "An edge gate accepts trades only in a narrow band of predicted edge, which leaves "
        "the regressor with little spread against a payoff that swings a full dollar. Read "
        "the slope next to its standard error: a large slope with a larger standard error is "
        "noise, not evidence.",
        "",
        "| Strategy | Slope | Std error | t | R² | Mean predicted edge | Mean realized edge |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in results.to_dict(orient="records"):
        lines.append(
            f"| {row['strategy']} | {_fmt(row.get('edge_slope'), '+.3f')} | "
            f"{_fmt(row.get('edge_slope_std_error'), '.3f')} | "
            f"{_fmt(row.get('edge_slope_t_stat'), '+.2f')} | "
            f"{_fmt(row.get('edge_r_squared'))} | "
            f"{_fmt(row.get('edge_mean_predicted_edge'), '+.4f')} | "
            f"{_fmt(row.get('edge_mean_realized_edge'), '+.4f')} |"
        )

    if not velocity.empty:
        lines += [
            "",
            "## Capital velocity",
            "",
            "A position held to settlement earns nothing once its price has "
            "converged to the forecast, while its capital stays unavailable to "
            "every other opportunity. Exiting early gives up the tail of the edge "
            "and pays the spread a second time, so whether it is worth doing "
            "cannot be read off ROI per trade -- that metric scores a six-month "
            "hold and a one-week turn identically.",
            "",
            "The column that decides it is **profit per capital-year**: dollars "
            "earned per dollar-year of capital actually committed.",
            "",
            "| Exit rule | Trades | Mean hold (days) | ROI per trade | Capital-years | Profit per capital-year | Total profit |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
        for row in velocity.to_dict(orient="records"):
            lines.append(
                f"| {row['exit_rule']} | {row['n_trades']:.0f} | "
                f"{_fmt(row['mean_holding_days'], '.1f')} | "
                f"{_fmt(row['roi_on_capital'], '+.4f')} | "
                f"{_fmt(row['capital_years'], ',.0f')} | "
                f"{_fmt(row['roi_per_capital_year'], '+.3f')} | "
                f"{row['total_profit']:+,.0f} |"
            )
        lines += [
            "",
            "Exit reasons: "
            + "; ".join(
                f"{row['exit_rule']} — {row['n_settlement']:.0f} settled, "
                f"{row['n_convergence']:.0f} converged, {row['n_stop_loss']:.0f} stopped"
                for row in velocity.to_dict(orient="records")
            )
            + ".",
            "",
            "A rule that raises profit per capital-year while lowering ROI per "
            "trade is doing exactly what it should. One that raises both is "
            "suspicious: early exit cannot manufacture edge, only recycle it.",
        ]

    if concentration.get("validation"):
        validation = concentration["validation"]
        lines += [
            "",
            "## Concentration",
            "",
            "Kelly is derived one wager at a time, so a book of independently "
            "sized positions under an aggregate cap is only as diversified as the "
            "positions are independent. Markets that settle together are one bet "
            "wearing several names, and the aggregate cap then describes a "
            "diversification the book does not have.",
            "",
            "**Which correlation matters depends on how the position ends.** A "
            "book held to settlement is exposed to joint settlement; a maker "
            "marked to market is exposed to joint price paths. Clustering this "
            "panel on price co-movement put 120 of 120 *independent* markets into "
            "multi-member clusters and produced groups 38% pure against 25% for "
            "chance -- every market's quote drifts toward its own truth as it "
            "matures, so any two co-move whether or not their outcomes are "
            "related. Settlement risk is therefore measured directly, by asking "
            "whether markets inside a candidate group agree with each other more "
            "often than markets across groups.",
            "",
            "| Grouping test | Value |",
            "|---|---:|",
            f"| Markets tested | {validation['n_markets']:.0f} |",
            f"| Groups | {validation['n_groups']:.0f} |",
            f"| Agreement within a group | {validation['within_concordance']:.3f} |",
            f"| Agreement across groups | {validation['cross_concordance']:.3f} |",
            "| Implied within-group outcome correlation | "
            f"{validation['implied_within_correlation']:+.3f} |",
            f"| Permutation p-value | {validation['p_value']:.3f} |",
            "",
        ]
        if concentration.get("sweep") is not None:
            sweep = concentration["sweep"]
            lines += [
                f"The grouping **{'does' if concentration['trusted'] else 'does not'}** predict "
                "joint settlement at the configured significance, so it "
                f"{'is' if concentration['trusted'] else 'is not'} sized against. Every row "
                "below is the same forecast and the same measured correlation; only the "
                "per-group exposure cap differs.",
                "",
                "| Group cap | Positions | Effective bets | Peak exposure to one group | Profit | Profit per capital-year |",
                "|---:|---:|---:|---:|---:|---:|",
            ]
            for row in sweep.to_dict(orient="records"):
                lines.append(
                    f"| {row['max_cluster_exposure']:.0%} | {row['n_positions']:.0f} | "
                    f"{row['effective_independent_bets']:.1f} | "
                    f"{row['peak_group_exposure']:.1%} | "
                    f"{row['total_profit']:+,.0f} | {row['roi_per_capital_year']:+.2f} |"
                )
            bound = sweep[sweep["peak_group_exposure"] >= sweep["max_cluster_exposure"] - 1e-9]
            lines += [
                "",
                "Read the peak-exposure column against the cap in the same row. Where the peak "
                "sits at the cap, the cap bound and shaped the book; where it sits comfortably "
                "below, the per-market limit was already holding the group under and the cap "
                "did nothing."
                + (
                    f" Here it starts binding at {bound['max_cluster_exposure'].max():.0%}."
                    if not bound.empty
                    else " Here it never binds at any swept level."
                ),
                "",
                "The profit column is not the thing to optimize against. These books hold "
                "dozens of trades whose outcomes are correlated by construction, so the "
                "differences between rows sit well inside the noise; the columns that carry "
                "information are the position and effective-bet counts, which are structural.",
                "",
                "A position count is not a bet count, and the gap between them is what the cap "
                "exists to close. Whether it needs to bind depends on how many markets in one "
                "group clear the edge gate at once, which is a property of the universe rather "
                "than something a default can know -- hence a sweep rather than a number.",
                "",
                "One consequence worth carrying into every other table in this report: when "
                "outcomes are correlated, the effective sample behind any performance estimate "
                "is nearer the group count than the observation count. The bootstrap intervals "
                "quoted elsewhere resample trades, not groups, so they are narrower than the "
                "truth.",
            ]

    if not resolution.empty:
        baseline_trades = resolution["n_trades"].iloc[0]
        lines += [
            "",
            "## Resolution risk",
            "",
            "A prediction market pays out on what the resolver decides, not on "
            "what happened. Questions get settled on technicalities, disputed, or "
            "voided. That risk is charged here twice: the forecast is discounted "
            "for it before sizing, and the simulation realizes it at the same rate.",
            "",
            "### How much can an edge absorb",
            "",
            "This table is analytic rather than simulated, so it carries no "
            "sampling noise. It reads: for a position entered at each price with "
            f"the configured {trade_config.min_edge:.0%} edge, the settlement "
            "failure rate at which expected value reaches zero.",
            "",
            "| Entry price | Forecast | Max tolerable resolution risk |",
            "|---:|---:|---:|",
        ]
        for entry in (0.10, 0.25, 0.50, 0.75, 0.90):
            forecast = min(entry + trade_config.min_edge, 0.99)
            tolerable = max_tolerable_resolution_risk(
                forecast, entry, trade_config.fee_bps, trade_config.resolution_recovery
            )
            lines.append(f"| {entry:.2f} | {forecast:.2f} | {tolerable:.1%} |")
        lines += [
            "",
            "Expensive contracts are the fragile ones. The same "
            f"{trade_config.min_edge:.0%} edge tolerates several times more "
            "settlement failure at a ten-cent entry than at ninety, because at "
            "ninety there is almost nothing above the entry price left to win. A "
            "strategy concentrated in high-priced favourites is betting on the "
            "resolver as much as on the outcome.",
            "",
            "### What it does to the strategy",
            "",
            "| Assumed resolution risk | Trades | Total profit | ROI per trade |",
            "|---:|---:|---:|---:|",
        ]
        for row in resolution.to_dict(orient="records"):
            lines.append(
                f"| {row['resolution_risk']:.0%} | {row['n_trades']:.0f} | "
                f"{row['total_profit']:+,.0f} | "
                f"{_fmt(row['roi_on_capital'], '+.4f')} |"
            )
        lines += [
            "",
            f"Read the trade count, not the P&L. The gate rejects more positions "
            f"as the assumed risk rises -- from {baseline_trades:.0f} trades at "
            f"zero down the column -- and the profit figures at the bottom rest "
            "on a sample too small to carry a conclusion.",
        ]

    lines += [
        "",
        "## Market making",
        "",
        "A taker pays the spread; a maker is paid it. On a venue quoting a few "
        "cents against a one-dollar payoff that is frequently larger than any "
        "forecast edge available, so it is the other half of the profitability "
        "question -- and it fails for a different reason.",
        "",
        "A resting quote is filled precisely when someone wants the other side, "
        "which is disproportionately when they know something. The simulation "
        "splits flow accordingly: a price move through a quote fills it and marks "
        "the position at the new price, and a configurable share of periods "
        "produce fills unrelated to any move. **All maker profit comes from that "
        "second group**, and its size is a property of the venue that price "
        "history cannot measure. It is therefore swept, not assumed.",
        "",
    ]
    for name, sweep in making.items():
        break_even = break_even_uninformed_rate(sweep)
        if np.isfinite(break_even):
            verdict = (
                f"Break-even uninformed fill rate: **{break_even:.1%}**. Below this "
                "share of benign flow the book loses money however tightly it quotes."
            )
        elif (sweep["total_pnl"] > 0).all():
            # Profitable with no benign flow at all means the quoted fair value
            # is carrying the book, not the spread.
            verdict = (
                "**Profitable across the entire swept range, including with no "
                "benign flow at all.** A maker that makes money on purely informed "
                "flow is being paid for its forecast, not for its spread."
            )
        else:
            verdict = (
                "**Never profitable in the swept range.** No assumption about flow "
                "composition inside 0-100% rescues this configuration."
            )
        lines += [
            f"### Quoting around: {name}",
            "",
            verdict,
            "",
            "| Uninformed fill rate | Fills | P&L | Quoted spread | Adverse selection | Capture ratio | Peak capital |",
            "|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for row in sweep.to_dict(orient="records"):
            lines.append(
                f"| {row['uninformed_fill_rate']:.0%} | {row['n_fills']:.0f} | "
                f"{row['total_pnl']:+,.0f} | {row['quoted_spread_value']:,.0f} | "
                f"{row['adverse_selection_pnl']:+,.0f} | "
                f"{_fmt(row['spread_capture_ratio'], '+.3f')} | "
                f"{row['peak_committed_capital']:,.0f} |"
            )
        if sweep["declined_fills"].sum() > 0:
            lines.append("")
            lines.append(
                "> The book ran out of cash during this sweep and declined fills. "
                "Raise `market_making.bankroll` or lower `quote_size` / "
                "`max_concurrent_markets`: these rows understate both the losses "
                "and the gains."
            )
        lines.append("")

    lines += [
        "Capture ratio is realized P&L over the spread that was quoted. One means "
        "every quoted cent was kept; zero or below means the flow took back more "
        "than the spread paid. Adverse selection is roughly constant across the "
        "sweep because it depends on how often the price moves, not on how much "
        "benign flow arrives alongside it.",
        "",
        "## Structural arbitrage self-test",
        "",
        f"The scanner was run against a synthetic snapshot containing {scan_planted} planted "
        f"basket mispricings and reported {scan_found}. Because the planted set is known "
        "exactly, this checks the scanner for both false negatives and false positives; it "
        "says nothing about how many such baskets exist on the live venue. Run "
        "`scripts/scan_polymarket_arbitrage.py --source live` for that.",
        "",
        "## How to read this",
        "",
        "1. Start with **Brier skill vs market**, as a fraction of the achievable ceiling. If "
        "it is not positive, the forecast has no edge and the trading columns are measuring "
        "luck plus frictions.",
        "2. Check that **Market price** trades rarely or loses. It has zero edge by "
        "definition, so profit from it would indicate a bug in the friction model.",
        "3. Compare against **Favourite** and **Longshot**. These always clear the edge gate "
        "without any information, so they price what trading on a false signal costs.",
        "4. Compare **Market-anchored** against **Logistic (unanchored)**. The unanchored "
        "entrant must re-estimate the coefficient on the market price from a few hundred "
        "independent settled markets; the anchored one takes that coefficient as one and "
        "learns only a correction. The gap between them is the cost of that free parameter.",
        "5. Only then read ROI, and read it next to the **edge realization** slope and the "
        "trade count. A high ROI on a few dozen binary settlements is not a result.",
        "",
        "## Limitations",
        "",
        "- Entries assume the quoted size is available; prediction-market books are thin and "
        "a real order moves them.",
        "- Resolution risk is charged at an assumed rate, not a measured one; the rate "
        "itself is the assumption, and the sweep above is the honest form of it.",
        "- Capital lock-up until settlement is modelled, but the opportunity cost of that "
        "capital is not.",
        "- Settled markets are a survivorship-inflected sample; markets that were voided or "
        "never resolved do not appear in the panel.",
        "- Multiple models were examined, which creates researcher degrees of freedom. The "
        "regularization strength is chosen inside each training window rather than from these "
        "results, but the choice of model family was not. Treat a single positive result as a "
        "hypothesis, not a finding.",
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


if __name__ == "__main__":
    main()
